### ISSUE TITLE
Persistent function errors

### ISSUE THREAD

**Issue by aalokkamble** [servian/bigquery-view-analyzer#10] opened 2020-01-22 12:45 UTC
Getting error while creating a tree with views having dependency on 'persistent functions'.

Error:

`google.api_core.exceptions.NotFound: 404 GET https://bigquery.googleapis.com/bigquery/v2/projects/.../functions : Not found: Table project:dataset.persistent_function`

```
Traceback (most recent call last):
  File "/usr/local/bin/bqva", line 10, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/bigquery_view_analyzer/cli.py", line 73, in tree
    formatted_tree = view.format_tree(show_status=status, show_key=key)
  File "/usr/local/lib/python3.7/site-packages/bigquery_view_analyzer/analyzer.py", line 128, in format_tree
    for pre, _, node in RenderTree(self.tree):
  File "/usr/local/lib/python3.7/site-packages/bigquery_view_analyzer/analyzer.py", line 103, in tree
    self._tree = self._build_tree(root_node)
  File "/usr/local/lib/python3.7/site-packages/bigquery_view_analyzer/analyzer.py", line 157, in _build_tree
    self._build_tree(child_node)
  File "/usr/local/lib/python3.7/site-packages/bigquery_view_analyzer/analyzer.py", line 155, in _build_tree
    child_table = self._get_table(project_id, dataset_id, table_id)
  File "/usr/local/lib/python3.7/site-packages/bigquery_view_analyzer/analyzer.py", line 138, in _get_table
    return client.get_table(view_ref)
  File "/usr/local/lib/python3.7/site-packages/google/cloud/bigquery/client.py", line 591, in get_table
    api_response = self._call_api(retry, method="GET", path=table_ref.path)
  File "/usr/local/lib/python3.7/site-packages/google/cloud/bigquery/client.py", line 487, in _call_api
    return call()
  File "/usr/local/lib/python3.7/site-packages/google/api_core/retry.py", line 286, in retry_wrapped_func
    on_error=on_error,
  File "/usr/local/lib/python3.7/site-packages/google/api_core/retry.py", line 184, in retry_target
    return target()
  File "/usr/local/lib/python3.7/site-packages/google/cloud/_http.py", line 421, in api_request
    raise exceptions.from_http_response(response)
```

**Comment by christippett** [comment] 2020-01-24 01:22
Hey @aalokkamble, are you able to share the DDL of the view you're analysing?

**Comment by courtney-lang** [comment] 2020-01-27 23:15
@christippett Looked into this issue a little bit. The cause is that BigQuery requires functions to be referenced in the same way tables are when creating views:

>[User Defined Functions - Limitations](https://cloud.google.com/bigquery/docs/reference/standard-sql/user-defined-functions#limitations)
>
>When referencing a persistent UDF from a logical view, you must fully qualify the name with the project and dataset. For example:
>
>```CREATE VIEW mydataset.sample_view AS SELECT `my-project`.mydataset.referencedFunction();```

There are a couple ways to handle this:
1. We make the `FROM|JOIN` part of the regex required instead of optional. This gets a little tricky though especially when joining with syntax
```
FROM `project`.dataset.table1,
     `project`.dataset.table2,
     `project`.dataset.table3
```

2. Implement a `try / except` in the analyzer. I tested this in the [_build_tree() function](https://github.com/servian/bigquery-view-analyzer/blob/master/src/bigquery_view_analyzer/analyzer.py#L155-L157):

```
try:
    child_table = self._get_table(project_id, dataset_id, table_id)
    child_node = TableNode(table=child_table, parent=table_node)
    self._build_tree(child_node)
except google.api_core.exceptions.NotFound:
    pass
```

The downside of this is if the view is referencing a table that has erroneously been dropped, it will skip over it in the status / authorization without telling the user that their view is broken. If that's not a huge deal, I have my forked branch with these changes [here](https://github.com/servian/bigquery-view-analyzer/compare/master...courtney-lang:try-except-table-not-found) and can open a pull request.

---

Example ddls:

Function:
```
CREATE FUNCTION _test.addFourAndDivide(x INT64, y INT64) AS ((x + 4) / y);
```

Table:
```
CREATE TABLE _test.udf_inputs AS
SELECT 1 as val
UNION ALL
SELECT 3 as val
UNION ALL
SELECT 4 as val
UNION ALL
SELECT 5 as val
```

View:
```
CREATE VIEW _test.udf_view_test AS
SELECT val AS udf_input, 
       `project`._test.addFourAndDivide(val, 2) AS udf_result
  FROM `project`._test.udf_inputs
```

**Comment by christippett** [comment] 2020-01-28 00:59
My thinking is that this could be solved using a regex pattern that excludes matches for any references that end in parentheses.

**Comment by courtney-lang** [comment] 2020-01-28 02:58
Oh, that's a good idea!

**Comment by christippett** [comment] 2020-01-28 06:47
@courtney-lang I don't suppose you'd like to contribute a fix for this?

**Comment by courtney-lang** [comment] 2020-01-28 22:22
@christippett Happy to! :smiley: 

https://github.com/servian/bigquery-view-analyzer/pull/11

**Comment by christippett** [comment] 2020-01-29 00:12
Legend @courtney-lang! Thanks :)

**Closed** 2020-01-29 00:13 UTC
Labels: bug, good first issue
